[package]
name = "client"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]

[dependencies]
server = { path = "../server", version = "0.1.0" }
rand = "^0.3"
tokio-core = "^0.1"
tokio-io = "^0.1"
bytes = "^0.4"
futures = "^0.1.17"
futures-cpupool = "^0.1.7"
clap = "^2.27.1"
